using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dosaic.Extensions.Localization.Generator
{
    [Generator]
    [ExcludeFromCodeCoverage]
    public class LocalizationGenerator : IIncrementalGenerator
    {
        private sealed class PropertyInfo
        {
            public string TypeName { get; }
            public string PropertyName { get; }
            public string En { get; }
            public string De { get; }

            public PropertyInfo(string typeName, string propertyName, string en, string de)
            {
                TypeName = typeName;
                PropertyName = propertyName;
                En = en;
                De = de;
            }
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var properties = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Dosaic.Extensions.Localization.LocalizedNameAttribute",
                    (node, _) => node is PropertyDeclarationSyntax,
                    (ctx, _) => ExtractInfo(ctx))
                .Where(p => p != null);

            var combined = properties.Collect().Combine(context.AnalyzerConfigOptionsProvider);

            context.RegisterSourceOutput(combined, (spc, source) =>
            {
                var (props, options) = source;
                spc.AddSource("EntityPropertyLabels.g.cs", GenerateLookupClass(props));

                options.GlobalOptions.TryGetValue("build_property.LocalizationJsonDeOutputPath", out var dePath);
                options.GlobalOptions.TryGetValue("build_property.LocalizationJsonEnOutputPath", out var enPath);

                if (!string.IsNullOrWhiteSpace(dePath))
                    WriteJsonFile(dePath, props, "de");
                if (!string.IsNullOrWhiteSpace(enPath))
                    WriteJsonFile(enPath, props, "en");
            });
        }

        private const string ClassHeader =
            """
            // <auto-generated/>
            using System.Collections.Generic;

            namespace Dosaic.Extensions.Localization
            {
                public static partial class EntityPropertyLabels
                {
                    private static readonly Dictionary<string, Dictionary<string, string>> Labels =
                        new Dictionary<string, Dictionary<string, string>>()
                        {
            """;

        private const string ClassFooter =
            """
                        };

                    public static string DefaultCulture = "en";

                    public static string Get(string typeName, string propertyName)
                        => Get(typeName, propertyName, DefaultCulture);

                    public static string Get(string typeName, string propertyName, string culture)
                    {
                        var key = typeName + "." + propertyName;
                        return Labels.TryGetValue(key, out var cultures) &&
                               cultures.TryGetValue(culture, out var label) ? label : propertyName;
                    }

                    public static string Get<T>(System.Linq.Expressions.Expression<System.Func<T, object>> propertySelector)
                        => Get<T>(propertySelector, DefaultCulture);

                    public static string Get<T>(System.Linq.Expressions.Expression<System.Func<T, object>> propertySelector, string culture)
                    {
                        System.Linq.Expressions.MemberExpression member;
                        if (propertySelector.Body is System.Linq.Expressions.MemberExpression direct)
                            member = direct;
                        else if (propertySelector.Body is System.Linq.Expressions.UnaryExpression unary &&
                                 unary.Operand is System.Linq.Expressions.MemberExpression unaryMember)
                            member = unaryMember;
                        else
                            throw new System.ArgumentException("Expression must be a property access.", nameof(propertySelector));
                        return Get(typeof(T).Name, member.Member.Name, culture);
                    }
                }
            }
            """;

        private static string GenerateLookupClass(ImmutableArray<PropertyInfo> props)
        {
            var sb = new StringBuilder();
            sb.AppendLine(ClassHeader);

            foreach (var prop in props)
            {
                if (prop == null) continue;
                sb.AppendLine(
                    $"                [\"{prop.TypeName}.{prop.PropertyName}\"] = " +
                    $"new Dictionary<string, string> {{ [\"en\"] = \"{Escape(prop.En)}\", [\"de\"] = \"{Escape(prop.De)}\" }},");
            }

            sb.Append(ClassFooter);
            return sb.ToString();
        }

        private static void WriteJsonFile(string path, ImmutableArray<PropertyInfo> props, string culture)
        {
            var grouped = new Dictionary<string, List<PropertyInfo>>();
            foreach (var prop in props)
            {
                if (prop == null) continue;
                if (!grouped.TryGetValue(prop.TypeName, out var list))
                    grouped[prop.TypeName] = list = new List<PropertyInfo>();
                list.Add(prop);
            }

            var sb = new StringBuilder();
            sb.AppendLine("{");

            var types = new List<string>(grouped.Keys);
            for (var i = 0; i < types.Count; i++)
            {
                var typeName = types[i];
                var members = grouped[typeName];
                sb.AppendLine($"  \"{EscapeJson(typeName)}\": {{");

                for (var j = 0; j < members.Count; j++)
                {
                    var prop = members[j];
                    var translation = GetTranslation(prop, culture);
                    var comma = j < members.Count - 1 ? "," : "";
                    sb.AppendLine($"    \"{EscapeJson(prop.PropertyName)}\": \"{EscapeJson(translation)}\"{comma}");
                }

                var typeComma = i < types.Count - 1 ? "," : "";
                sb.AppendLine($"  }}{typeComma}");
            }

            sb.Append("}");

#pragma warning disable RS1035
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);
            File.WriteAllText(path, sb.ToString());
#pragma warning restore RS1035
        }

        private static string GetTranslation(PropertyInfo prop, string culture)
        {
            if (culture == "en") return prop.En;
            if (culture == "de") return prop.De;
            return prop.PropertyName;
        }

        private static PropertyInfo ExtractInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (!(ctx.TargetSymbol is IPropertySymbol property))
                return null;

            var typeName = property.ContainingType?.Name;
            if (typeName == null)
                return null;

            var attr = ctx.Attributes.FirstOrDefault();
            if (attr == null)
                return null;

            var en = "";
            var de = "";

            if (attr.ConstructorArguments.Length >= 1)
                en = attr.ConstructorArguments[0].Value as string ?? "";
            if (attr.ConstructorArguments.Length >= 2)
                de = attr.ConstructorArguments[1].Value as string ?? "";

            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "En")
                    en = named.Value.Value as string ?? en;
                else if (named.Key == "De")
                    de = named.Value.Value as string ?? de;
            }

            return new PropertyInfo(typeName, property.Name, en, de);
        }

        private static string Escape(string value)
            => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string EscapeJson(string value)
            => value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
    }
}
