using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dosaic.Extensions.Localization.Generator
{
    [Generator]
    [ExcludeFromCodeCoverage]
    public class LocalizationGenerator : IIncrementalGenerator
    {
        private sealed class LabelInfo
        {
            public string GroupName { get; }   // type name — used for grouping and as key prefix
            public string MemberName { get; }  // null for class/enum level entries
            public string En { get; }
            public string De { get; }

            public string Key => MemberName != null ? $"{GroupName}.{MemberName}" : GroupName;

            public LabelInfo(string groupName, string memberName, string en, string de)
            {
                GroupName = groupName;
                MemberName = memberName;
                En = en;
                De = de;
            }
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var labels = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Dosaic.Extensions.Localization.LocalizedNameAttribute",
                    (node, _) => node is PropertyDeclarationSyntax
                              || node is FieldDeclarationSyntax
                              || node is EnumMemberDeclarationSyntax
                              || node is ClassDeclarationSyntax
                              || node is RecordDeclarationSyntax
                              || node is StructDeclarationSyntax
                              || node is EnumDeclarationSyntax,
                    (ctx, _) => ExtractInfo(ctx))
                .Where(p => p != null);

            var combined = labels.Collect().Combine(context.AnalyzerConfigOptionsProvider);

            context.RegisterSourceOutput(combined, (spc, source) =>
            {
                var (infos, options) = source;
                spc.AddSource("EntityPropertyLabels.g.cs", GenerateLookupClass(infos));

                options.GlobalOptions.TryGetValue("build_property.LocalizationJsonDeOutputPath", out var dePath);
                options.GlobalOptions.TryGetValue("build_property.LocalizationJsonEnOutputPath", out var enPath);

                if (!string.IsNullOrWhiteSpace(dePath))
                    WriteJsonFile(dePath, infos, "de");
                if (!string.IsNullOrWhiteSpace(enPath))
                    WriteJsonFile(enPath, infos, "en");
            });
        }

        private const string ClassHeader =
            """
            // <auto-generated/>
            using System.Collections.Generic;

            namespace Dosaic.Extensions.Localization
            {
                public static partial class EntityPropertyLabels
                {
                    public static readonly Dictionary<string, Dictionary<string, string>> Labels =
                        new Dictionary<string, Dictionary<string, string>>()
                        {
            """;

        private const string ClassFooter =
            """
                        };

                    public static Locale DefaultCulture = Locale.En;

                    private static string ToCode(Locale culture) => culture == Locale.En ? "en" : "de";

                    public static string Get(string key)
                        => Get(key, DefaultCulture);

                    public static string Get(string key, Locale culture)
                    {
                        var code = ToCode(culture);
                        return Labels.TryGetValue(key, out var cultures) &&
                               cultures.TryGetValue(code, out var label) ? label : key;
                    }

                    public static string Get<T>()
                        => Get(typeof(T).Name, DefaultCulture);

                    public static string Get<T>(Locale culture)
                        => Get(typeof(T).Name, culture);

                    public static string Get(System.Enum value)
                        => Get(value, DefaultCulture);

                    public static string Get(System.Enum value, Locale culture)
                        => Get(value.GetType().Name + "." + value.ToString(), culture);

                    public static string Get<T>(System.Linq.Expressions.Expression<System.Func<T, object>> memberSelector)
                        => Get<T>(memberSelector, DefaultCulture);

                    public static string Get<T>(System.Linq.Expressions.Expression<System.Func<T, object>> memberSelector, Locale culture)
                    {
                        System.Linq.Expressions.MemberExpression member;
                        if (memberSelector.Body is System.Linq.Expressions.MemberExpression direct)
                            member = direct;
                        else if (memberSelector.Body is System.Linq.Expressions.UnaryExpression unary &&
                                 unary.Operand is System.Linq.Expressions.MemberExpression unaryMember)
                            member = unaryMember;
                        else
                            throw new System.ArgumentException("Expression must be a member access.", nameof(memberSelector));
                        return Get(typeof(T).Name + "." + member.Member.Name, culture);
                    }
                }
            }
            """;

        private static string GenerateLookupClass(ImmutableArray<LabelInfo> infos)
        {
            var sb = new StringBuilder();
            sb.AppendLine(ClassHeader);

            foreach (var info in infos)
            {
                if (info == null) continue;
                sb.AppendLine(
                    $"                [\"{info.Key}\"] = " +
                    $"new Dictionary<string, string> {{ [\"en\"] = \"{Escape(info.En)}\", [\"de\"] = \"{Escape(info.De)}\" }},");
            }

            sb.Append(ClassFooter);
            return sb.ToString();
        }

        private static void WriteJsonFile(string path, ImmutableArray<LabelInfo> infos, string culture)
        {
            var grouped = new Dictionary<string, List<LabelInfo>>();
            foreach (var info in infos)
            {
                if (info == null) continue;
                if (!grouped.TryGetValue(info.GroupName, out var list))
                    grouped[info.GroupName] = list = new List<LabelInfo>();
                list.Add(info);
            }

            var sb = new StringBuilder();
            sb.AppendLine("{");

            var groups = new List<string>(grouped.Keys);
            for (var i = 0; i < groups.Count; i++)
            {
                var groupName = groups[i];
                var members = grouped[groupName];
                sb.AppendLine($"  \"{EscapeJson(groupName)}\": {{");

                for (var j = 0; j < members.Count; j++)
                {
                    var info = members[j];
                    var memberKey = info.MemberName != null ? EscapeJson(info.MemberName) : "$";
                    var translation = GetTranslation(info, culture);
                    var comma = j < members.Count - 1 ? "," : "";
                    sb.AppendLine($"    \"{memberKey}\": \"{EscapeJson(translation)}\"{comma}");
                }

                var groupComma = i < groups.Count - 1 ? "," : "";
                sb.AppendLine($"  }}{groupComma}");
            }

            sb.Append("}");

#pragma warning disable RS1035
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);
            File.WriteAllText(path, sb.ToString());
#pragma warning restore RS1035
        }

        private static string GetTranslation(LabelInfo info, string culture)
        {
            if (culture == "en") return info.En;
            if (culture == "de") return info.De;
            return info.MemberName ?? info.GroupName;
        }

        private static LabelInfo ExtractInfo(GeneratorAttributeSyntaxContext ctx)
        {
            var attr = ctx.Attributes.FirstOrDefault();
            if (attr == null) return null;

            var en = "";
            var de = "";

            if (attr.ConstructorArguments.Length >= 1)
                en = attr.ConstructorArguments[0].Value as string ?? "";
            if (attr.ConstructorArguments.Length >= 2)
                de = attr.ConstructorArguments[1].Value as string ?? "";

            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "En")
                    en = named.Value.Value as string ?? en;
                else if (named.Key == "De")
                    de = named.Value.Value as string ?? de;
            }

            if (ctx.TargetSymbol is IPropertySymbol prop)
            {
                var typeName = prop.ContainingType?.Name;
                return typeName == null ? null : new LabelInfo(typeName, prop.Name, en, de);
            }

            if (ctx.TargetSymbol is IFieldSymbol field)
            {
                var typeName = field.ContainingType?.Name;
                return typeName == null ? null : new LabelInfo(typeName, field.Name, en, de);
            }

            if (ctx.TargetSymbol is INamedTypeSymbol namedType)
                return new LabelInfo(namedType.Name, null, en, de);

            return null;
        }

        private static string Escape(string value)
            => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string EscapeJson(string value)
            => value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
    }
}
