using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dosaic.Extensions.Localization.Generator
{
    [Generator]
    [ExcludeFromCodeCoverage]
    public class LocalizationGenerator : IIncrementalGenerator
    {
        private sealed class PropertyInfo
        {
            public string TypeName { get; }
            public string PropertyName { get; }
            public string En { get; }
            public string De { get; }

            public PropertyInfo(string typeName, string propertyName, string en, string de)
            {
                TypeName = typeName;
                PropertyName = propertyName;
                En = en;
                De = de;
            }
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var properties = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Dosaic.Extensions.Localization.LocalizedNameAttribute",
                    (node, _) => node is PropertyDeclarationSyntax,
                    (ctx, _) => ExtractInfo(ctx))
                .Where(p => p != null);

            context.RegisterSourceOutput(properties.Collect(), (spc, props) =>
            {
                spc.AddSource("EntityPropertyLabels.g.cs", GenerateLookupClass(props));
            });
        }

        private const string ClassHeader =
            """
            // <auto-generated/>
            using System.Collections.Generic;

            namespace Dosaic.Extensions.Localization
            {
                public static partial class EntityPropertyLabels
                {
                    private static readonly Dictionary<string, Dictionary<string, string>> Labels =
                        new Dictionary<string, Dictionary<string, string>>()
                        {
            """;

        private const string ClassFooter =
            """
                        };

                    public static string DefaultCulture = "en";

                    public static string Get(string typeName, string propertyName)
                        => Get(typeName, propertyName, DefaultCulture);

                    public static string Get(string typeName, string propertyName, string culture)
                    {
                        var key = typeName + "." + propertyName;
                        return Labels.TryGetValue(key, out var cultures) &&
                               cultures.TryGetValue(culture, out var label) ? label : propertyName;
                    }

                    public static string Get<T>(System.Linq.Expressions.Expression<System.Func<T, object>> propertySelector)
                        => Get<T>(propertySelector, DefaultCulture);

                    public static string Get<T>(System.Linq.Expressions.Expression<System.Func<T, object>> propertySelector, string culture)
                    {
                        System.Linq.Expressions.MemberExpression member;
                        if (propertySelector.Body is System.Linq.Expressions.MemberExpression direct)
                            member = direct;
                        else if (propertySelector.Body is System.Linq.Expressions.UnaryExpression unary &&
                                 unary.Operand is System.Linq.Expressions.MemberExpression unaryMember)
                            member = unaryMember;
                        else
                            throw new System.ArgumentException("Expression must be a property access.", nameof(propertySelector));
                        return Get(typeof(T).Name, member.Member.Name, culture);
                    }
                }
            }
            """;

        private static string GenerateLookupClass(ImmutableArray<PropertyInfo> props)
        {
            var sb = new StringBuilder();
            sb.AppendLine(ClassHeader);

            foreach (var prop in props)
            {
                if (prop == null) continue;
                sb.AppendLine(
                    $"                [\"{prop.TypeName}.{prop.PropertyName}\"] = " +
                    $"new Dictionary<string, string> {{ [\"en\"] = \"{Escape(prop.En)}\", [\"de\"] = \"{Escape(prop.De)}\" }},");
            }

            sb.Append(ClassFooter);
            return sb.ToString();
        }

        private static PropertyInfo ExtractInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (!(ctx.TargetSymbol is IPropertySymbol property))
                return null;

            var typeName = property.ContainingType?.Name;
            if (typeName == null)
                return null;

            var attr = ctx.Attributes.FirstOrDefault();
            if (attr == null)
                return null;

            var en = "";
            var de = "";

            if (attr.ConstructorArguments.Length >= 1)
                en = attr.ConstructorArguments[0].Value as string ?? "";
            if (attr.ConstructorArguments.Length >= 2)
                de = attr.ConstructorArguments[1].Value as string ?? "";

            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "En")
                    en = named.Value.Value as string ?? en;
                else if (named.Key == "De")
                    de = named.Value.Value as string ?? de;
            }

            return new PropertyInfo(typeName, property.Name, en, de);
        }

        private static string Escape(string value)
            => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
