# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: dotnet-main
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: install
      run: dotnet restore

    - name: format
      run: dotnet format --verify-no-changes --no-restore

    - name: build
      run: dotnet build -c Release

    - name: test & cover
      run: dotnet test --collect "Code Coverage;Format=Xml;CoverageFileName=coverage.xml" --results-directory "./test-results" --no-restore --nologo -c Release --logger trx

    - name: publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          test-results/**/*.trx
        comment_mode: 'off'

    - name: publish coverage results
      uses: im-open/code-coverage-report-generator@4
      with:
        reports: '*/**/coverage.xml'
        targetdir: './coverage-results'
        title: dotnet code coverage
        reporttypes: 'MarkdownSummary;'
        assemblyfilters: +Dosaic*

    - name: coverage check
      id: dotnet-coverage-check
      #You may also reference just the major or major.minor version
      uses: im-open/process-code-coverage-summary@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-file: './coverage-results/Summary.md'
        report-name: '.NET Code Coverage'      # Default: Code Coverage Results
        check-name: 'dotnet code coverage'            # Default: code coverage
        create-status-check: false                     # Default: true
        create-pr-comment: false                     # Default: true
        update-comment-if-one-exists: false            # Default: true
        update-comment-key: 'dotnet'                  # Default: N/A, used to further identify a comment to update if this action is used more than once in a workflow
        ignore-threshold-failures: false              # Default: false
        line-threshold: 80                            # Default: 0, which means thresholds are not applied
        branch-threshold: 0                         # Default: 0, which means thresholds are not applied

    - name: upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report-${{ matrix.runs-on }}
        path: coverage-results/**
        overwrite: true

    - name: write job summary
      run: cat ./coverage-results/Summary.md >> $GITHUB_STEP_SUMMARY

